package workspace

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"maps"
	"slices"
	"strings"

	"github.com/byranZA/smith/internal/connection"
)

// The fragment's place on the box. Box-level tools and env land in a
// user-level config fragment smith owns whole, beside — never inside — the
// operator's own ~/.config/mise/config.toml, which smith neither reads nor
// writes. mise reads conf.d/*.toml at lower precedence than that file, so a
// hand-written global config on the box outranks the blueprint: the nearer,
// more specific declaration wins, and an operator overriding a version never
// has to fight a generated file.
const (
	// fragmentDir is the directory under the smith user's home holding the
	// generated fragment.
	fragmentDir = ".config/mise/conf.d"
	// fragmentFile is the generated fragment's name. It is smith's, and the
	// name says so.
	fragmentFile = "smith.toml"
	// miseDir is where mise is installed under the smith user's home when the
	// box does not already have it. It is a single binary, not an apt package.
	miseDir = ".local/bin"
	// miseFile is the mise binary's name, which is also what it is invoked by
	// when the box already has it on PATH.
	miseFile = "mise"
)

// Fragment is the generated mise config one toolchain unit writes: where the
// file lands, the tools it pins, and the env it exports.
//
// smith owns the file whole and writes it by replacement, so nothing here is
// merged into what the box already holds. The values in Env are references as
// the blueprint declared them — they are resolved when the fragment is
// generated, never carried resolved through a plan.
type Fragment struct {
	// Path is where the generated file lands, absolute.
	Path string
	// Mise is where mise is installed if the box does not already have it.
	Mise string
	// Tools are the toolchain versions the fragment pins, keyed by tool name.
	Tools map[string]string
	// Env are the environment variables the fragment exports, keyed by
	// variable name, each value still the reference the blueprint declared.
	Env map[string]string
}

// header opens every generated fragment. An operator who opens the file is
// told whose it is, that an edit will not survive the next converge, and where
// their own mise config stands — which is untouched, and above this one.
const header = `# Generated by smith — do not edit.
#
# ` + "`smith workspace converge`" + ` writes this file whole from the box's blueprint,
# so anything added here is lost on the next run. smith never reads or writes
# your own mise config at ~/.config/mise/config.toml, and that file outranks
# this one.
`

// Generate renders the mise config smith owns: the tools it pins and the env
// it exports, under a header saying the file is generated.
//
// It is pure and total — it reads nothing, writes nothing and resolves
// nothing, so the bytes that reach a box are the bytes a golden file pins. The
// env values it is given are already resolved: a reference is dead provenance
// by the time it is written into a file mise will export verbatim.
//
// Keys are written in sorted order, because a map has lost the order the
// operator wrote them in and a fragment that shuffled between runs would
// rewrite a file nothing had changed. A section the blueprint declares nothing
// for is left out rather than written empty.
func Generate(tools, env map[string]string) []byte {
	var b strings.Builder
	b.WriteString(header)
	section(&b, "tools", tools)
	section(&b, "env", env)
	return []byte(b.String())
}

// section writes one table of the fragment, keys in sorted order, or nothing
// at all when the blueprint declared nothing for it.
func section(b *strings.Builder, name string, values map[string]string) {
	if len(values) == 0 {
		return
	}
	fmt.Fprintf(b, "\n[%s]\n", name)
	for _, key := range slices.Sorted(maps.Keys(values)) {
		fmt.Fprintf(b, "%s = %s\n", key, tomlString(values[key]))
	}
}

// tomlString renders a value as a TOML basic string. A token or a path may
// carry a quote or a backslash, and one written raw would truncate the
// document into something mise reads as a different file entirely.
func tomlString(value string) string {
	escaped := strings.ReplaceAll(value, `\`, `\\`)
	escaped = strings.ReplaceAll(escaped, `"`, `\"`)
	return `"` + escaped + `"`
}

// fragmentMode is the generated fragment's permissions. It exports the
// blueprint's env with every value resolved, so it holds provisioned secrets
// and is readable by the account that consumes them and nothing else.
const fragmentMode = 0o600

// installer is where mise's own install script lives. mise is a single binary,
// not an apt package, so this is how a box that has none gets one.
const installer = "https://mise.run"

// convergeToolchain gives the box its toolchain: mise installed, the generated
// fragment holding what the blueprint declares, and the pinned versions
// installed.
//
// The values are resolved before anything is installed, so a blueprint smith
// cannot resolve fails having changed nothing rather than half way through an
// install. The fragment is written whole and never merged — smith owns the
// file — and it is written only when its bytes differ, so a converged re-run
// moves no modification time.
//
// mise is then asked to install what the fragment pins. smith never runs `mise
// use`: that writes into ~/.config/mise/config.toml, which is mise's own file
// and may hold the operator's settings, and smith writes generated files by
// whole-file replacement.
func convergeToolchain(ctx context.Context, env Env, f Fragment, progress io.Writer) (string, error) {
	values, err := resolve(env.Secret, f.Env)
	if err != nil {
		return "", err
	}
	done, err := ensureMise(ctx, env.Command, f.Mise, progress)
	if err != nil {
		return "", err
	}
	wrote, err := writeFragment(f.Path, Generate(f.Tools, values))
	if err != nil {
		return "", err
	}
	done = append(done, wrote)
	if len(f.Tools) == 0 {
		return strings.Join(done, "; "), nil
	}
	if err := env.Command.Run(ctx, miseInvocation(f.Mise), []string{"install"}, nil, progress, progress); err != nil {
		return "", fmt.Errorf("install the pinned versions with mise: %w", err)
	}
	return strings.Join(append(done, "installed "+pinned(f.Tools)), "; "), nil
}

// resolve turns each declared value into the value it references, on the box
// smith is running on. A reference that does not resolve fails the step by the
// variable's name: exporting the reference itself would put the string
// "env:GITHUB_TOKEN" in a token's place and surface later as a clone that
// cannot authenticate.
func resolve(resolver Resolver, env map[string]string) (map[string]string, error) {
	if len(env) == 0 {
		return nil, nil
	}
	if resolver == nil {
		return nil, errors.New("resolve the blueprint's env: this box has no resolver to read a reference with")
	}
	values := make(map[string]string, len(env))
	for _, name := range slices.Sorted(maps.Keys(env)) {
		value, err := resolver(env[name])
		if err != nil {
			return nil, fmt.Errorf("resolve the value of %s: %w", name, err)
		}
		values[name] = value
	}
	return values, nil
}

// ensureMise leaves the box with an invocable mise and reports what it took.
//
// A box that already has one — on PATH, or installed where smith puts it — is
// left alone. Otherwise mise's own install script puts the binary at the path
// the plan named, and the result is probed rather than assumed, so a run that
// could not reach the installer fails here rather than at the first version it
// tries to install.
func ensureMise(ctx context.Context, run Runner, path string, progress io.Writer) ([]string, error) {
	if invocable(ctx, run, miseFile) || invocable(ctx, run, path) {
		return []string{"mise already installed"}, nil
	}
	script := fmt.Sprintf("curl -fsSL %s | MISE_INSTALL_PATH=%s sh",
		connection.ShellArg(installer), connection.ShellArg(path))
	if err := run.Run(ctx, "sh", []string{"-c", script}, nil, progress, progress); err != nil {
		return nil, fmt.Errorf("install mise from %s: %w", installer, err)
	}
	if !invocable(ctx, run, path) {
		return nil, fmt.Errorf("mise is still not invocable at %s after installing it", path)
	}
	return []string{"installed mise at " + path}, nil
}

// invocable reports whether mise answers at the given command. A box that has
// never had mise answers the probe with a failure, which is the answer rather
// than an error to report.
func invocable(ctx context.Context, run Runner, command string) bool {
	return run.Run(ctx, command, []string{"--version"}, nil, io.Discard, io.Discard) == nil
}

// miseInvocation is what mise is invoked by: the binary smith installed, which
// is also where a box that already had one is probed. Every invocation is
// `mise exec` or `mise install` — never `mise activate`, which does not fire
// in the non-interactive and daemon-started shells smith and its agents run
// in.
func miseInvocation(path string) string {
	if path == "" {
		return miseFile
	}
	return path
}

// writeFragment puts the generated bytes at path and reports what it did to
// the file. It is check-before-change: a fragment already holding these bytes
// is left where it is, modification time and all.
func writeFragment(path string, data []byte) (string, error) {
	current, exists, err := onBox(path)
	if err != nil {
		return "", err
	}
	if exists && bytes.Equal(current, data) {
		return "unchanged " + path, nil
	}
	if err := put(path, data, fragmentMode); err != nil {
		return "", err
	}
	if exists {
		return "rewrote " + path, nil
	}
	return "wrote " + path, nil
}

// pinned names the versions the fragment pins, the way the operator reads them
// back: sorted, so the report is the same from one run to the next.
func pinned(tools map[string]string) string {
	named := make([]string, 0, len(tools))
	for _, tool := range slices.Sorted(maps.Keys(tools)) {
		named = append(named, tool+" "+tools[tool])
	}
	return strings.Join(named, ", ")
}
