package workspace

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"maps"
	"slices"
	"strings"

	"github.com/byranZA/smith/internal/connection"
	"github.com/byranZA/smith/internal/staging"
)

// The fragment's place on the box. Box-level tools and env land in a
// user-level config fragment smith owns whole, beside — never inside — the
// operator's own ~/.config/mise/config.toml, which smith neither reads nor
// writes. mise reads conf.d/*.toml at lower precedence than that file, so a
// hand-written global config on the box outranks the blueprint: the nearer,
// more specific declaration wins, and an operator overriding a version never
// has to fight a generated file.
const (
	// fragmentDir is the directory under the smith user's home holding the
	// generated fragment.
	fragmentDir = ".config/mise/conf.d"
	// fragmentFile is the generated fragment's name. It is smith's, and the
	// name says so.
	fragmentFile = "smith.toml"
	// miseDir is where mise is installed under the smith user's home when the
	// box does not already have it. It is a single binary, not an apt package.
	miseDir = ".local/bin"
	// miseFile is the mise binary's name, which is also what it is invoked by
	// when the box already has it on PATH.
	miseFile = "mise"
	// repoFragmentFile is the generated config a repo's own tools and env land
	// in, written in the repo's directory — above every worktree, so mise's
	// walk-up finds it and smith never dirties a checkout.
	repoFragmentFile = "mise.toml"
)

// Fragment is the generated mise config one toolchain unit writes: where the
// file lands, the tools it pins, and the env it exports.
//
// smith owns the file whole and writes it by replacement, so nothing here is
// merged into what the box already holds. Env names the variables the fragment
// exports rather than carrying their values: the values were resolved on the
// operator's machine and staged on the box, and they are read from there when
// the fragment is generated.
type Fragment struct {
	// Path is where the generated file lands, absolute.
	Path string
	// Dir is the directory mise resolves this config from, empty for the
	// user-level fragment mise reads wherever it runs. A repo's config is
	// found by walking up from the repo's own directory, so the install that
	// follows it is run with mise pointed there.
	Dir string
	// Mise is where mise is installed if the box does not already have it.
	Mise string
	// Repo is the repo whose env the fragment exports, empty for the box's
	// own. It is the scope the staged values are read by.
	Repo string
	// Tools are the toolchain versions the fragment pins, keyed by tool name.
	Tools map[string]string
	// Env are the names of the environment variables the fragment exports, in
	// sorted order. Their values come from what `machine setup` staged.
	Env []string
}

// header opens every generated config, box-level and per-repo alike. An
// operator who opens the file is told whose it is, that an edit will not
// survive the next converge, and that the declaration nearer to the work — the
// mise.toml a repo commits — outranks what smith generates.
const header = `# Generated by smith — do not edit.
#
# ` + "`smith workspace converge`" + ` writes this file whole from the box's blueprint,
# so anything added here is lost on the next run. smith never reads or writes
# your own mise config at ~/.config/mise/config.toml, and a mise.toml committed
# inside a repo is nearer than anything smith generates and outranks it.
`

// Generate renders the mise config smith owns: the tools it pins and the env
// it exports, under a header saying the file is generated.
//
// It is pure and total — it reads nothing, writes nothing and resolves
// nothing, so the bytes that reach a box are the bytes a golden file pins. The
// env values it is given are already resolved: a reference is dead provenance
// by the time it is written into a file mise will export verbatim.
//
// Keys are written in sorted order, because a map has lost the order the
// operator wrote them in and a fragment that shuffled between runs would
// rewrite a file nothing had changed. A section the blueprint declares nothing
// for is left out rather than written empty.
func Generate(tools, env map[string]string) []byte {
	var b strings.Builder
	b.WriteString(header)
	section(&b, "tools", tools)
	section(&b, "env", env)
	return []byte(b.String())
}

// section writes one table of the fragment, keys in sorted order, or nothing
// at all when the blueprint declared nothing for it.
func section(b *strings.Builder, name string, values map[string]string) {
	if len(values) == 0 {
		return
	}
	fmt.Fprintf(b, "\n[%s]\n", name)
	for _, key := range slices.Sorted(maps.Keys(values)) {
		fmt.Fprintf(b, "%s = %s\n", key, tomlString(values[key]))
	}
}

// tomlString renders a value as a TOML basic string. A token or a path may
// carry a quote or a backslash, and one written raw would truncate the
// document into something mise reads as a different file entirely.
func tomlString(value string) string {
	escaped := strings.ReplaceAll(value, `\`, `\\`)
	escaped = strings.ReplaceAll(escaped, `"`, `\"`)
	return `"` + escaped + `"`
}

// fragmentMode is the generated fragment's permissions. It exports the
// blueprint's env with every value resolved, so it holds provisioned secrets
// and is readable by the account that consumes them and nothing else.
const fragmentMode = 0o600

// installer is where mise's own install script lives. mise is a single binary,
// not an apt package, so this is how a box that has none gets one.
const installer = "https://mise.run"

// convergeToolchain gives the box its toolchain: mise installed, the generated
// fragment holding what the blueprint declares, and the pinned versions
// installed.
//
// The staged values are read before anything is installed, so a variable with
// no staged value fails having changed nothing rather than half way through an
// install. The fragment is written whole and never merged — smith owns the
// file — and it is written only when its bytes differ, so a converged re-run
// moves no modification time.
//
// mise is then asked to install what the fragment pins. smith never runs `mise
// use`: that writes into ~/.config/mise/config.toml, which is mise's own file
// and may hold the operator's settings, and smith writes generated files by
// whole-file replacement.
func convergeToolchain(ctx context.Context, env Env, m *mise, f Fragment, progress io.Writer) (string, error) {
	values, err := stagedValues(env.StateRoot, f.Repo, f.Env)
	if err != nil {
		return "", err
	}
	exe, done, err := m.ensure(ctx, env.Command, f.Mise, progress)
	if err != nil {
		return "", err
	}
	wrote, err := writeFragment(f.Path, Generate(f.Tools, values))
	if err != nil {
		return "", err
	}
	done = append(done, wrote)
	if len(f.Tools) == 0 {
		return strings.Join(done, "; "), nil
	}
	if err := env.Command.Run(ctx, exe, installArgs(f.Dir), nil, progress, progress); err != nil {
		return "", fmt.Errorf("install the pinned versions with mise: %w", err)
	}
	return strings.Join(append(done, "installed "+pinned(f.Tools)), "; "), nil
}

// installArgs is the mise invocation that installs what a fragment pins. mise
// resolves its config by walking up from where it runs, so a fragment written
// above a repo's worktrees is installed with mise pointed at that directory —
// there is no second mise and no store of the repo's own, only a config
// selecting a version out of the one shared install directory.
func installArgs(dir string) []string {
	if dir == "" {
		return []string{"install"}
	}
	return []string{"--cd", dir, "install"}
}

// stagedValues reads the value of every variable the fragment exports out of
// what `machine setup` staged under root.
//
// Nothing is resolved here, for any scheme. env:GITHUB_TOKEN names a variable
// in the operator's shell and file:~/.secrets/token a path on their disk, so a
// box reading either would export what it happens to hold rather than what the
// operator declared — silently the wrong token, or nothing at all. The values
// were read on the operator's machine at `machine setup` and staged; a variable
// with no staged value fails the step by name rather than falling back to the
// box.
func stagedValues(root, repo string, names []string) (map[string]string, error) {
	if len(names) == 0 {
		return nil, nil
	}
	values := make(map[string]string, len(names))
	for _, name := range names {
		value, err := staging.ReadValue(root, repo, name)
		if err != nil {
			return nil, fmt.Errorf("export %s: %w", name, err)
		}
		values[name] = value
	}
	return values, nil
}

// mise is the mise executable one converge run invokes, proven once and shared
// by every unit that needs one.
//
// Which executable that is depends on the box: one that already had mise
// answers to whatever is on PATH, and one that did not answers only at the
// path smith installed a binary to. They are different executables, and a unit
// deciding for itself which to invoke can pick the one that is not there — a
// toolchain that installs no version and a clone that fails with "command not
// found" on a box whose mise works. Proving it once removes the choice.
type mise struct {
	// exe is the proven executable, empty until the run has needed one.
	exe string
}

// ensure returns the executable this run invokes mise by, proving it on the
// first call and answering from that proof afterwards. install is where the
// binary is put on a box that has none.
//
// The report it returns beside the executable is what proving it took, empty
// on every call after the first: the run installs mise once and says so once.
func (m *mise) ensure(ctx context.Context, run Runner, install string, progress io.Writer) (string, []string, error) {
	if m.exe != "" {
		return m.exe, nil, nil
	}
	exe, done, err := ensureMise(ctx, run, install, progress)
	if err != nil {
		return "", nil, err
	}
	m.exe = exe
	return exe, done, nil
}

// ensureMise leaves the box with an invocable mise and reports which
// executable that is, and what it took.
//
// A box that already has one — on PATH, or installed where smith puts it — is
// left alone and answers by the name that proved it. Otherwise mise's own
// install script puts the binary at the path the plan named, and the result is
// probed rather than assumed, so a run that could not reach the installer
// fails here rather than at the first version it tries to install.
//
// Every invocation that follows is `mise exec` or `mise install` — never `mise
// activate`, which does not fire in the non-interactive and daemon-started
// shells smith and its agents run in.
func ensureMise(ctx context.Context, run Runner, install string, progress io.Writer) (string, []string, error) {
	for _, exe := range []string{miseFile, install} {
		if invocable(ctx, run, exe) {
			return exe, []string{"mise already installed at " + exe}, nil
		}
	}
	script := fmt.Sprintf("curl -fsSL %s | MISE_INSTALL_PATH=%s sh",
		connection.ShellArg(installer), connection.ShellArg(install))
	if err := run.Run(ctx, "sh", []string{"-c", script}, nil, progress, progress); err != nil {
		return "", nil, fmt.Errorf("install mise from %s: %w", installer, err)
	}
	if !invocable(ctx, run, install) {
		return "", nil, fmt.Errorf("mise is still not invocable at %s after installing it", install)
	}
	return install, []string{"installed mise at " + install}, nil
}

// invocable reports whether mise answers at the given command. A box that has
// never had mise answers the probe with a failure, which is the answer rather
// than an error to report.
func invocable(ctx context.Context, run Runner, command string) bool {
	return run.Run(ctx, command, []string{"--version"}, nil, io.Discard, io.Discard) == nil
}

// writeFragment puts the generated bytes at path and reports what it did to
// the file. It is check-before-change: a fragment already holding these bytes
// is left where it is, modification time and all.
func writeFragment(path string, data []byte) (string, error) {
	current, exists, err := onBox(path)
	if err != nil {
		return "", err
	}
	if exists && bytes.Equal(current, data) {
		return "unchanged " + path, nil
	}
	if err := put(path, data, fragmentMode); err != nil {
		return "", err
	}
	if exists {
		return "rewrote " + path, nil
	}
	return "wrote " + path, nil
}

// pinned names the versions the fragment pins, the way the operator reads them
// back: sorted, so the report is the same from one run to the next.
func pinned(tools map[string]string) string {
	named := make([]string, 0, len(tools))
	for _, tool := range slices.Sorted(maps.Keys(tools)) {
		named = append(named, tool+" "+tools[tool])
	}
	return strings.Join(named, ", ")
}
