package workspace

import (
	"bytes"
	"context"
	"fmt"
	"io/fs"
	"maps"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"
	"time"

	"github.com/byranZA/smith/internal/blueprint"
	"github.com/byranZA/smith/internal/staging"
)

// TestPlanToolchain drives the pure derivation of the toolchain unit: what the
// blueprint has to declare for the box to get one, and what the unit carries.
func TestPlanToolchain(t *testing.T) {
	tests := []struct {
		name string
		b    blueprint.Blueprint
		want []Fragment
	}{
		{
			name: "declared tools are pinned in the smith-owned fragment",
			b:    blueprint.Blueprint{Tools: map[string]string{"node": "20", "go": "1.23"}},
			want: []Fragment{{
				Path:  "/home/smith/.config/mise/conf.d/smith.toml",
				Mise:  "/home/smith/.local/bin/mise",
				Tools: map[string]string{"node": "20", "go": "1.23"},
			}},
		},
		{
			name: "declared env alone still plans the fragment that exports it",
			b:    blueprint.Blueprint{Env: map[string]string{"GITHUB_TOKEN": "env:GITHUB_TOKEN"}},
			want: []Fragment{{
				Path: "/home/smith/.config/mise/conf.d/smith.toml",
				Mise: "/home/smith/.local/bin/mise",
				Env:  []string{"GITHUB_TOKEN"},
			}},
		},
		{
			name: "a repo alone plans the toolchain, because a clone runs under mise",
			b:    blueprint.Blueprint{Repos: []blueprint.Repo{{Name: "acme", URL: "git@example.com:acme.git"}}},
			want: []Fragment{{
				Path: "/home/smith/.config/mise/conf.d/smith.toml",
				Mise: "/home/smith/.local/bin/mise",
			}},
		},
		{
			name: "a blueprint with no toolchain and no repo plans none",
			b:    blueprint.Blueprint{Packages: []string{"ripgrep"}},
			want: nil,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var got []Fragment
			for _, unit := range Plan(tt.b, "/home/smith") {
				if unit.Step == Toolchain {
					got = append(got, unit.Fragment)
				}
			}
			if len(got) != len(tt.want) {
				t.Fatalf("Plan() planned %d toolchain units, want %d: %+v", len(got), len(tt.want), got)
			}
			for i, tc := range got {
				if tc.Path != tt.want[i].Path || tc.Mise != tt.want[i].Mise {
					t.Errorf("Plan() toolchain %d paths = %q, %q, want %q, %q", i, tc.Path, tc.Mise, tt.want[i].Path, tt.want[i].Mise)
				}
				if !maps.Equal(tc.Tools, tt.want[i].Tools) {
					t.Errorf("Plan() toolchain %d tools = %v, want %v", i, tc.Tools, tt.want[i].Tools)
				}
				if !slices.Equal(tc.Env, tt.want[i].Env) {
					t.Errorf("Plan() toolchain %d env = %v, want %v", i, tc.Env, tt.want[i].Env)
				}
			}
		})
	}
}

// TestPlanToolchainIsPure proves a caller that mutates a planned unit cannot
// reach back into the blueprint it was planned from.
func TestPlanToolchainIsPure(t *testing.T) {
	b := blueprint.Blueprint{Tools: map[string]string{"node": "20"}}
	for _, unit := range Plan(b, "/home/smith") {
		if unit.Step == Toolchain {
			unit.Fragment.Tools["node"] = "22"
		}
	}
	if b.Tools["node"] != "20" {
		t.Errorf("blueprint tools = %v after a caller mutated the plan, want node 20", b.Tools)
	}
}

// TestGenerate pins the bytes of the generated fragment against the golden
// file, header and all: the file is what mise reads, so its exact shape is the
// behaviour rather than an implementation detail.
func TestGenerate(t *testing.T) {
	got := Generate(
		map[string]string{"node": "20", "go": "1.23"},
		map[string]string{"NODE_ENV": "production", "GITHUB_TOKEN": "ghp_example"},
	)

	want, err := os.ReadFile(filepath.Join("testdata", "fragment.toml"))
	if err != nil {
		t.Fatalf("read the golden fragment: %v", err)
	}
	if string(got) != string(want) {
		t.Errorf("Generate() =\n%s\nwant\n%s", got, want)
	}
}

// TestGenerateOmitsAnUndeclaredSection proves a fragment declares only what the
// blueprint did: an empty section would tell mise nothing and read as a tool
// list smith had forgotten to fill in.
func TestGenerateOmitsAnUndeclaredSection(t *testing.T) {
	got := string(Generate(map[string]string{"node": "20"}, nil))

	if !strings.Contains(got, "[tools]") {
		t.Errorf("Generate() = %q, want it to pin the declared tool", got)
	}
	if strings.Contains(got, "[env]") {
		t.Errorf("Generate() = %q, want no env section for a blueprint declaring none", got)
	}
}

// TestGenerateCarriesTheGeneratedFileHeader proves the operator who opens the
// file is told whose it is and that an edit will not survive.
func TestGenerateCarriesTheGeneratedFileHeader(t *testing.T) {
	got := string(Generate(nil, nil))

	if !strings.HasPrefix(got, "# Generated by smith") {
		t.Errorf("Generate() = %q, want it to open with a generated-file header", got)
	}
	if !strings.Contains(got, "config.toml") {
		t.Errorf("Generate() = %q, want the header to name the operator's own config as untouched", got)
	}
}

// TestGenerateQuotesAValueThatWouldBreakTheDocument proves a value carrying a
// quote or a backslash — a Windows-style path, a token with an escape in it —
// stays one TOML string rather than truncating the file into nonsense.
func TestGenerateQuotesAValueThatWouldBreakTheDocument(t *testing.T) {
	got := string(Generate(nil, map[string]string{"AWKWARD": `a"b\c`}))

	if !strings.Contains(got, `AWKWARD = "a\"b\\c"`) {
		t.Errorf("Generate() = %q, want the quote and backslash escaped", got)
	}
}

// convergeOnBox runs the stage over what a blueprint declares, against a box
// and a home of the test's own, and returns what it did and what it streamed.
func convergeOnBox(t *testing.T, box *fakeBox, home string, b blueprint.Blueprint) (Result, string) {
	t.Helper()
	return convergeIn(t, box, t.TempDir(), home, b)
}

// operatorValue stands in for the operator's own resolver, which runs on their
// machine at `machine setup` and never on the box: it answers the references
// that machine can read and nothing else.
func operatorValue(ref string) (string, error) {
	switch ref {
	case "env:GITHUB_TOKEN":
		return "ghp_fromtheoperator", nil
	case "literal:production":
		return "production", nil
	default:
		return "", fmt.Errorf("nothing resolves %q", ref)
	}
}

// stageEnv puts the values of a blueprint's env under a box state directory the
// way `machine setup` does: resolved on the operator's machine, staged on the
// box, and read back there by name.
func stageEnv(t *testing.T, root string, b blueprint.Blueprint) {
	t.Helper()
	sources := func(ref string) (string, error) { return "bytes of " + ref, nil }
	tree, err := staging.Resolve(staging.Plan(nil, b), sources, operatorValue)
	if err != nil {
		t.Fatalf("resolve the blueprint's env on the operator's machine: %v", err)
	}
	path := staging.EnvPathIn(root)
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		t.Fatalf("make the box state directory: %v", err)
	}
	if err := os.WriteFile(path, tree.Env.File.Bytes, 0o600); err != nil {
		t.Fatalf("stage the env: %v", err)
	}
}

// fragmentPath is where the generated fragment lands under a home.
func fragmentPath(home string) string {
	return filepath.Join(home, ".config", "mise", "conf.d", "smith.toml")
}

// TestConvergeInstallsMiseWhenTheBoxLacksIt proves a box with no mise gets one,
// and that what the stage runs afterwards is the binary it just installed.
func TestConvergeInstallsMiseWhenTheBoxLacksIt(t *testing.T) {
	home := t.TempDir()
	box := &fakeBox{installed: map[string]bool{}}
	b := blueprint.Blueprint{Tools: map[string]string{"node": "20"}}

	result, progress := convergeOnBox(t, box, home, b)

	if result.Failed() {
		t.Fatalf("Result.Failed() = true, want false: %s", result.Report())
	}
	if !box.ran("mise.run") {
		t.Errorf("the stage ran %v, want it to install mise on a box that has none", box.calls)
	}
	if want := filepath.Join(home, ".local", "bin", "mise"); box.miseAt != want {
		t.Errorf("mise is invocable at %q after the stage installed it, want %q", box.miseAt, want)
	}
	if !strings.Contains(progress, "mise") {
		t.Errorf("progress = %q, want the toolchain step reported as it completes", progress)
	}
}

// TestConvergeLeavesAnInstalledMiseAlone proves a box that already has mise is
// not handed another copy of it.
func TestConvergeLeavesAnInstalledMiseAlone(t *testing.T) {
	home := t.TempDir()
	box := &fakeBox{installed: map[string]bool{}, hasMise: true}

	convergeOnBox(t, box, home, blueprint.Blueprint{Tools: map[string]string{"node": "20"}})

	if box.ran("mise.run") {
		t.Errorf("the stage ran %v, want no install on a box that already has mise", box.calls)
	}
}

// TestConvergePinsToolsInTheGeneratedFragment proves the blueprint's tools
// reach the file mise reads, and that the versions are then installed.
func TestConvergePinsToolsInTheGeneratedFragment(t *testing.T) {
	home := t.TempDir()
	box := &fakeBox{installed: map[string]bool{}, hasMise: true}
	b := blueprint.Blueprint{Tools: map[string]string{"node": "20", "go": "1.23"}}

	result, _ := convergeOnBox(t, box, home, b)

	if result.Failed() {
		t.Fatalf("Result.Failed() = true, want false: %s", result.Report())
	}
	got := held(t, fragmentPath(home))
	for _, want := range []string{`node = "20"`, `go = "1.23"`} {
		if !strings.Contains(got, want) {
			t.Errorf("fragment = %q, want it to pin %s", got, want)
		}
	}
	if !box.ran("mise install") {
		t.Errorf("the stage ran %v, want it to install the pinned versions", box.calls)
	}
}

// TestConvergeExportsEnvThroughTheFragment proves a declared variable reaches
// the box with its value, rather than with the reference the operator wrote.
func TestConvergeExportsEnvThroughTheFragment(t *testing.T) {
	home := t.TempDir()
	box := &fakeBox{installed: map[string]bool{}, hasMise: true}
	b := blueprint.Blueprint{Env: map[string]string{"GITHUB_TOKEN": "env:GITHUB_TOKEN"}}

	result, _ := convergeOnBox(t, box, home, b)

	if result.Failed() {
		t.Fatalf("Result.Failed() = true, want false: %s", result.Report())
	}
	if got := held(t, fragmentPath(home)); !strings.Contains(got, `GITHUB_TOKEN = "ghp_fromtheoperator"`) {
		t.Errorf("fragment = %q, want it to export the staged value", got)
	}
}

// TestConvergeExportsTheStagedValueRatherThanTheBoxsOwn proves the reference is
// read on the operator's machine and never again: a box holding a variable of
// the same name exports the value that was staged for it, not its own. The two
// are different strings on purpose, because a box quietly exporting its own
// GITHUB_TOKEN would authenticate as something other than the blueprint said.
func TestConvergeExportsTheStagedValueRatherThanTheBoxsOwn(t *testing.T) {
	home := t.TempDir()
	box := &fakeBox{installed: map[string]bool{}, hasMise: true}
	b := blueprint.Blueprint{Env: map[string]string{"GITHUB_TOKEN": "env:GITHUB_TOKEN"}}
	t.Setenv("GITHUB_TOKEN", "ghp_fromtheboxenv")

	result, _ := convergeOnBox(t, box, home, b)

	if result.Failed() {
		t.Fatalf("Result.Failed() = true, want false: %s", result.Report())
	}
	got := held(t, fragmentPath(home))
	if strings.Contains(got, "ghp_fromtheboxenv") {
		t.Errorf("fragment = %q, want the reference resolved on the operator's machine, not this box", got)
	}
	if !strings.Contains(got, `GITHUB_TOKEN = "ghp_fromtheoperator"`) {
		t.Errorf("fragment = %q, want it to export the staged value", got)
	}
}

// TestConvergeRefusesAVariableWithNoStagedValue proves a variable the staged
// blueprint declares but has no staged value for fails the step by name,
// rather than reading the box's own environment or exporting the reference as
// though it were a token.
func TestConvergeRefusesAVariableWithNoStagedValue(t *testing.T) {
	home := t.TempDir()
	box := &fakeBox{installed: map[string]bool{}, hasMise: true}
	b := blueprint.Blueprint{Env: map[string]string{"GITHUB_TOKEN": "env:GITHUB_TOKEN"}}
	t.Setenv("GITHUB_TOKEN", "ghp_fromtheboxenv")

	var progress bytes.Buffer
	env := Env{Command: box, StateRoot: t.TempDir()}
	result, err := Converge(context.Background(), env, Plan(b, home), &progress)
	if err != nil {
		t.Fatalf("Converge() error = %v, want nil", err)
	}

	if !result.Failed() {
		t.Fatalf("Result.Failed() = false, want true: %s", result.Report())
	}
	if err := result.Outcomes[0].Err; err == nil || !strings.Contains(err.Error(), "GITHUB_TOKEN") {
		t.Errorf("outcome error = %v, want it to name the variable with no staged value", err)
	}
	if _, err := os.Stat(fragmentPath(home)); !os.IsNotExist(err) {
		t.Errorf("a fragment was written for a blueprint whose value was never staged")
	}
}

// TestConvergeNeverTouchesTheOperatorsOwnMiseConfig proves the file mise calls
// its own is neither read nor written: it is where the operator's settings
// live, and it outranks smith's fragment on purpose.
func TestConvergeNeverTouchesTheOperatorsOwnMiseConfig(t *testing.T) {
	home := t.TempDir()
	own := filepath.Join(home, ".config", "mise", "config.toml")
	if err := os.MkdirAll(filepath.Dir(own), 0o700); err != nil {
		t.Fatalf("make the operator's mise config directory: %v", err)
	}
	if err := os.WriteFile(own, []byte("[tools]\nnode = \"18\"\n"), 0o600); err != nil {
		t.Fatalf("write the operator's mise config: %v", err)
	}
	before := modTime(t, own)
	box := &fakeBox{installed: map[string]bool{}, hasMise: true}

	convergeOnBox(t, box, home, blueprint.Blueprint{Tools: map[string]string{"node": "20"}})

	if got := held(t, own); got != "[tools]\nnode = \"18\"\n" {
		t.Errorf("the operator's own mise config = %q, want it unchanged", got)
	}
	if after := modTime(t, own); !after.Equal(before) {
		t.Errorf("the operator's own mise config was rewritten at %v, want it untouched", after)
	}
	if box.ran("use") {
		t.Errorf("the stage ran %v, want no mise use — it would write the operator's own config", box.calls)
	}
	if box.ran("activate") {
		t.Errorf("the stage ran %v, want no mise activate — it does not fire in the shells smith runs in", box.calls)
	}
}

// TestConvergeReconvergesAChangedVersion proves a blueprint whose version has
// moved rewrites the fragment and installs the new one.
func TestConvergeReconvergesAChangedVersion(t *testing.T) {
	home := t.TempDir()
	box := &fakeBox{installed: map[string]bool{}, hasMise: true}
	convergeOnBox(t, box, home, blueprint.Blueprint{Tools: map[string]string{"node": "20"}})

	box.calls = nil
	convergeOnBox(t, box, home, blueprint.Blueprint{Tools: map[string]string{"node": "22"}})

	if got := held(t, fragmentPath(home)); !strings.Contains(got, `node = "22"`) {
		t.Errorf("fragment = %q, want it to pin the version the blueprint now declares", got)
	}
	if !box.ran("mise install") {
		t.Errorf("the stage ran %v, want the new version installed", box.calls)
	}
}

// TestConvergeLeavesAnUnchangedFragmentAlone proves a converged re-run moves no
// modification time, which is the check-before-change property the whole stage
// carries.
func TestConvergeLeavesAnUnchangedFragmentAlone(t *testing.T) {
	home := t.TempDir()
	box := &fakeBox{installed: map[string]bool{}, hasMise: true}
	b := blueprint.Blueprint{Tools: map[string]string{"node": "20"}}
	convergeOnBox(t, box, home, b)
	before := modTime(t, fragmentPath(home))

	result, _ := convergeOnBox(t, box, home, b)

	if result.Failed() {
		t.Fatalf("Result.Failed() = true, want false: %s", result.Report())
	}
	if after := modTime(t, fragmentPath(home)); !after.Equal(before) {
		t.Errorf("the fragment was rewritten at %v, want it left alone at %v", after, before)
	}
}

// modTime is when the box last wrote path, and fails the test when the box
// holds nothing there.
func modTime(t *testing.T, path string) time.Time {
	t.Helper()
	info, err := os.Stat(path)
	if err != nil {
		t.Fatalf("read the modification time of %s: %v", path, err)
	}
	return info.ModTime()
}

// TestPlanRepoToolchain drives the pure derivation of a repo's own toolchain
// unit: what the repo has to declare to earn one, and where the generated file
// lands.
func TestPlanRepoToolchain(t *testing.T) {
	tests := []struct {
		name string
		b    blueprint.Blueprint
		want []Fragment
	}{
		{
			name: "a repo's tools override is pinned above its worktrees",
			b: blueprint.Blueprint{Repos: []blueprint.Repo{{
				Name:  "acme",
				URL:   "git@example.com:acme.git",
				Tools: map[string]string{"node": "22"},
			}}},
			want: []Fragment{{
				Path:  "/home/smith/workspace/acme/mise.toml",
				Dir:   "/home/smith/workspace/acme",
				Mise:  "/home/smith/.local/bin/mise",
				Tools: map[string]string{"node": "22"},
			}},
		},
		{
			name: "a repo declaring only env still earns the file that exports it",
			b: blueprint.Blueprint{Repos: []blueprint.Repo{{
				Name: "acme",
				URL:  "git@example.com:acme.git",
				Env:  map[string]string{"NODE_ENV": "literal:production"},
			}}},
			want: []Fragment{{
				Path: "/home/smith/workspace/acme/mise.toml",
				Dir:  "/home/smith/workspace/acme",
				Mise: "/home/smith/.local/bin/mise",
				Env:  []string{"NODE_ENV"},
			}},
		},
		{
			name: "a repo overriding nothing takes the box's toolchain and earns no file",
			b: blueprint.Blueprint{Repos: []blueprint.Repo{{
				Name: "acme",
				URL:  "git@example.com:acme.git",
			}}},
			want: nil,
		},
		{
			name: "an unnamed repo's file lands under the name its url gives it",
			b: blueprint.Blueprint{Repos: []blueprint.Repo{{
				URL:   "git@example.com:acme.git",
				Tools: map[string]string{"node": "22"},
			}}},
			want: []Fragment{{
				Path:  "/home/smith/workspace/acme/mise.toml",
				Dir:   "/home/smith/workspace/acme",
				Mise:  "/home/smith/.local/bin/mise",
				Tools: map[string]string{"node": "22"},
			}},
		},
		{
			name: "the file follows the workspace root the blueprint overrides",
			b: blueprint.Blueprint{Workspace: "~/code", Repos: []blueprint.Repo{{
				Name:  "acme",
				URL:   "git@example.com:acme.git",
				Tools: map[string]string{"node": "22"},
			}}},
			want: []Fragment{{
				Path:  "/home/smith/code/acme/mise.toml",
				Dir:   "/home/smith/code/acme",
				Mise:  "/home/smith/.local/bin/mise",
				Tools: map[string]string{"node": "22"},
			}},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var got []Fragment
			for _, unit := range Plan(tt.b, "/home/smith") {
				if unit.Step == Toolchain && unit.Fragment.Dir != "" {
					got = append(got, unit.Fragment)
				}
			}
			if len(got) != len(tt.want) {
				t.Fatalf("Plan() planned %d repo toolchain units, want %d: %+v", len(got), len(tt.want), got)
			}
			for i, f := range got {
				if f.Path != tt.want[i].Path || f.Mise != tt.want[i].Mise {
					t.Errorf("Plan() repo toolchain %d paths = %q, %q, want %q, %q", i, f.Path, f.Mise, tt.want[i].Path, tt.want[i].Mise)
				}
				if !maps.Equal(f.Tools, tt.want[i].Tools) {
					t.Errorf("Plan() repo toolchain %d tools = %v, want %v", i, f.Tools, tt.want[i].Tools)
				}
				if !slices.Equal(f.Env, tt.want[i].Env) {
					t.Errorf("Plan() repo toolchain %d env = %v, want %v", i, f.Env, tt.want[i].Env)
				}
			}
		})
	}
}

// repoFragmentPath is where a repo's generated mise config lands under a home.
func repoFragmentPath(home, repo string) string {
	return filepath.Join(home, "workspace", repo, "mise.toml")
}

// TestGenerateRepoFragment pins the bytes of a repo's generated config against
// the golden file. It is the same pure seam the box-level fragment is rendered
// through — only the values and the file it lands in differ — so the header an
// operator opening the repo's file reads is pinned here too.
func TestGenerateRepoFragment(t *testing.T) {
	got := Generate(
		map[string]string{"node": "22"},
		map[string]string{"NODE_ENV": "production"},
	)

	want, err := os.ReadFile(filepath.Join("testdata", "repo.toml"))
	if err != nil {
		t.Fatalf("read the golden repo config: %v", err)
	}
	if string(got) != string(want) {
		t.Errorf("Generate() =\n%s\nwant\n%s", got, want)
	}
}

// TestConvergePinsRepoToolsAboveTheWorktrees proves a repo's override reaches
// the file mise walks up to find, that the version is installed with mise
// pointed at that directory, and that nothing is written inside a worktree.
func TestConvergePinsRepoToolsAboveTheWorktrees(t *testing.T) {
	home := t.TempDir()
	box := newBox()
	box.hasMise = true
	b := blueprint.Blueprint{Repos: []blueprint.Repo{{
		Name:  "acme",
		URL:   "git@example.com:acme.git",
		Tools: map[string]string{"node": "22"},
	}}}

	result, _ := convergeOnBox(t, box, home, b)

	if result.Failed() {
		t.Fatalf("Result.Failed() = true, want false: %s", result.Report())
	}
	path := repoFragmentPath(home, "acme")
	if got := held(t, path); !strings.Contains(got, `node = "22"`) {
		t.Errorf("%s = %q, want it to pin the repo's override", path, got)
	}
	dir := filepath.Dir(path)
	if !box.ran("--cd " + dir + " install") {
		t.Errorf("the stage ran %v, want the repo's versions installed from %s", box.calls, dir)
	}
	if written := writtenUnder(t, filepath.Join(dir, "worktrees")); len(written) > 0 {
		t.Errorf("the stage wrote %v inside a worktree, want nothing there", written)
	}
}

// TestConvergeCarriesTheGeneratedHeaderIntoTheRepoConfig proves the operator
// who opens the repo's file is told it is smith's and that an edit is lost.
func TestConvergeCarriesTheGeneratedHeaderIntoTheRepoConfig(t *testing.T) {
	home := t.TempDir()
	box := newBox()
	box.hasMise = true
	b := blueprint.Blueprint{Repos: []blueprint.Repo{{
		Name:  "acme",
		URL:   "git@example.com:acme.git",
		Tools: map[string]string{"node": "22"},
	}}}

	convergeOnBox(t, box, home, b)

	if got := held(t, repoFragmentPath(home, "acme")); !strings.HasPrefix(got, "# Generated by smith") {
		t.Errorf("the repo's config = %q, want it to open with a generated-file header", got)
	}
}

// TestConvergeExportsRepoEnvThroughTheRepoConfig proves a repo's own variable
// reaches the same file with its value resolved, rather than the reference the
// operator wrote.
func TestConvergeExportsRepoEnvThroughTheRepoConfig(t *testing.T) {
	home := t.TempDir()
	box := newBox()
	box.hasMise = true
	b := blueprint.Blueprint{Repos: []blueprint.Repo{{
		Name: "acme",
		URL:  "git@example.com:acme.git",
		Env:  map[string]string{"NODE_ENV": "literal:production"},
	}}}

	result, _ := convergeOnBox(t, box, home, b)

	if result.Failed() {
		t.Fatalf("Result.Failed() = true, want false: %s", result.Report())
	}
	if got := held(t, repoFragmentPath(home, "acme")); !strings.Contains(got, `NODE_ENV = "production"`) {
		t.Errorf("the repo's config = %q, want it to export the resolved value", got)
	}
}

// TestConvergeSharesOneInstallStoreAcrossRepos proves two repos on the same
// version are two selections of one install rather than two installs: both run
// through the one mise the box holds, and neither is given a store of its own.
func TestConvergeSharesOneInstallStoreAcrossRepos(t *testing.T) {
	home := t.TempDir()
	box := newBox()
	box.hasMise = true
	b := blueprint.Blueprint{Repos: []blueprint.Repo{
		{Name: "acme", URL: "git@example.com:acme.git", Tools: map[string]string{"node": "22"}},
		{Name: "api", URL: "git@example.com:api.git", Tools: map[string]string{"node": "22"}},
	}}

	result, _ := convergeOnBox(t, box, home, b)

	if result.Failed() {
		t.Fatalf("Result.Failed() = true, want false: %s", result.Report())
	}
	var installs [][]string
	for _, argv := range box.calls {
		if len(argv) > 0 && argv[0] != "sh" && strings.Contains(strings.Join(argv, " "), "install") {
			installs = append(installs, argv)
		}
	}
	if len(installs) != 2 {
		t.Fatalf("the stage ran %d installs, want one per repo: %v", len(installs), box.calls)
	}
	for _, argv := range installs {
		if argv[0] != installs[0][0] {
			t.Errorf("an install ran %v, want the one mise %s the run proved", argv, installs[0][0])
		}
		for _, arg := range argv {
			if strings.Contains(arg, "data-dir") || strings.Contains(arg, "MISE_DATA_DIR") {
				t.Errorf("an install ran %v, want no store of its own", argv)
			}
		}
	}
	for _, repo := range []string{"acme", "api"} {
		if got := held(t, repoFragmentPath(home, repo)); !strings.Contains(got, `node = "22"`) {
			t.Errorf("%s config = %q, want it to select the shared version", repo, got)
		}
	}
}

// writtenUnder is every file the box holds below root, relative to it, and
// nothing at all when the box holds no such directory.
func writtenUnder(t *testing.T, root string) []string {
	t.Helper()
	var found []string
	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() {
			found = append(found, path)
		}
		return nil
	})
	if err != nil && !os.IsNotExist(err) {
		t.Fatalf("read what the box holds under %s: %v", root, err)
	}
	return found
}

// TestConvergeRunsTheMiseTheBoxAlreadyHas proves the executable every step
// invokes is the one the probe answered at. A box carrying mise on PATH has
// nothing where smith would have installed one, so a step rebuilding that path
// for itself would install no version and clone no repo — on a box whose mise
// works.
func TestConvergeRunsTheMiseTheBoxAlreadyHas(t *testing.T) {
	home := t.TempDir()
	box := newBox()
	box.hasMise = true
	b := declaresRepo("acme")
	b.Tools = map[string]string{"node": "20"}

	result, _ := convergeOnBox(t, box, home, b)

	if result.Failed() {
		t.Fatalf("Result.Failed() = true, want false: %s", result.Report())
	}
	installPath := filepath.Join(home, ".local", "bin", "mise")
	for _, argv := range box.calls {
		if argv[0] == installPath {
			t.Errorf("the stage ran %v, want the mise on PATH that answered the probe", argv)
		}
	}
	if box.miseAt != "" {
		t.Errorf("the stage installed mise at %q, want the one on PATH left to answer for itself", box.miseAt)
	}
	if !box.ranExact(miseFile, "install") {
		t.Errorf("the stage ran %v, want the pinned version installed by the mise on PATH", box.calls)
	}
	if !box.ranExact(miseFile, "exec", "--", "git", "clone", "--bare", b.Repos[0].URL,
		filepath.Join(home, "workspace", "acme", cloneDir)) {
		t.Errorf("the stage ran %v, want the clone run under the mise the box has", box.calls)
	}
}

// TestConvergeRunsTheMiseItInstalled proves the opposite provenance: a box that
// had none is left invoking the binary smith put there, by the path it put it
// at, rather than a bare `mise` that is on no PATH.
func TestConvergeRunsTheMiseItInstalled(t *testing.T) {
	home := t.TempDir()
	box := newBox()
	b := declaresRepo("acme")
	b.Tools = map[string]string{"node": "20"}

	result, _ := convergeOnBox(t, box, home, b)

	if result.Failed() {
		t.Fatalf("Result.Failed() = true, want false: %s", result.Report())
	}
	installPath := filepath.Join(home, ".local", "bin", "mise")
	if box.miseAt != installPath {
		t.Fatalf("the stage installed mise at %q, want %q", box.miseAt, installPath)
	}
	if !box.ran(installPath + " exec -- git clone") {
		t.Errorf("the stage ran %v, want the clone run under the mise it installed", box.calls)
	}
	for _, argv := range box.calls {
		if argv[0] == miseFile && len(argv) > 1 && argv[1] != "--version" {
			t.Errorf("the stage ran %v, want the installed mise rather than a bare one", argv)
		}
	}
}

// TestConvergeProvesMiseOnce proves the executable is established once for the
// whole run and handed on: a plan with a toolchain and a repo probes mise once,
// so the two steps cannot end up on different answers.
func TestConvergeProvesMiseOnce(t *testing.T) {
	home := t.TempDir()
	box := newBox()
	box.hasMise = true
	b := declaresRepo("acme")
	b.Tools = map[string]string{"node": "20"}

	convergeOnBox(t, box, home, b)

	var probes int
	for _, argv := range box.calls {
		if len(argv) == 2 && isMise(argv[0]) && argv[1] == "--version" {
			probes++
		}
	}
	if probes != 1 {
		t.Errorf("the stage probed mise %d times, want the one proof the run shares: %v", probes, box.calls)
	}
}
